# -*- coding: utf-8 -*-
"""Teoria Computacion S1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aAOP66-eOAJ8tT1QwKZjql1F20f9S3on

## **INTRODUCCION**
**SEMANA 1**

**a es un elemento**

Escalar es un elemento

**A es un conjunto**

Matriz, lista es un conjunto
"""

a = 10 
A = {1, 2, 3, 4, 10}

"""A pertenece a A"""

a in A

"""a no pertenece a A"""

a not in A

"""A es conjunto finito"""

A = {1, 2, 3, 4, 10}

"""N es un conjunto infinito"""

N = {1, 2, 3, ...}

"""a es un escalar

{a} es un conjunto
"""

a + {a}

"""Es un cojunto de un cojunto

Es un elemento de un conjunto
"""

{{a,b}} ≠ {a,b}

"""**A es un subcojunto de B**

ya que todos los elementos de A estan B
"""

A={1,2,3}
B={0,1,2,3,4,5,6}

"""A⊆B
A subconjunto de B

B⊆C
B subconjunto de C

A⊆C
A subconjunto de C


https://medium.com/@LuisMBaezCo/todo-lo-que-debes-saber-de-conjuntos-en-python-set-91d9eb33c3
"""

A={1,2}
B={1,2,3,4}
C={1,2,3,4,5,6}

print('A es subconjunto de B')
print(A.issubset(B))

print('B es subconjunto de C')
print(B.issubset(C))

print('A es subconjunto de C')
print(A.issubset(C))

"""Ø Conjunto vacio

 Ø ⊆ A, para todo conjunto A

 Un conjunto vacio puede ser subconjunto de otro conjunto vacio.
"""

A = set()
B = set()

A.issubset(B)

"""Discretos una cantidad "exactos"

Continuo para clasificar en "rangos"

**Conjunto Potencia (Finito/Infinito)**

Hardcode
"""

A = {10, 20, 30}

[set(), 
 set([10]), set([20]), set([30]), 
 set([10, 20]), set([10, 30]), set([20, 30]), set([10, 20, 30])]

"""Con Librerias"""

from sympy import FiniteSet
C = FiniteSet(1, 2, 3)
C.powerset()

"""**Union**"""

A={1,2,3}
B={4,5,6}

A.union(B)

"""**Intersección**"""

A={1, 2, 3, 4, 5}
B={3, 4, 5, 6}

A.intersection(B)

"""**EJEMPLO 1**"""

A = {0,1,2,3}
B = {-1,-2,-3}

print('Union de A con B')
print(A.union(B))

print('Interseccion A con B')
print(A.intersection(B))

"""**EJEMPLO 2**"""

A = {0,1,2,3}
B = None

print('Union de A con B')
print(A.union(B))

print('Interseccion A con B')
print(A.intersection(B))

"""Respuesta:

AuB = A

AnB = null

### **Diferentes Cojuntos con diferentes Simbolos**

**Palabras en Ingles**

Simbolos, letras *(Apostrofes, guion)*'
"""

∑b = {1,0}

"""**Enteros**

Caracteres Digitos *{0,1,2,3,4,5,6,7,8,9}*
"""

∑d = {0,1,2,3,4,5,6,7,8,9}

"""*Conjunto infinito, simbolos finitos*"""

Lc = {3388, 3864, 3795, 8966, 8792, ...}

"""*∑ alfabeto   ↑*

**C, Java**

Simbolos formados de una coleccion finito

*Colecciones finitos de secuencias de simbolos de longitud finito

### **Definiciones**

**Alfabeto**: Conjunto no vacio y finito de simbolos.

Si ∑ es un alfabeto, σ e Σ denota que σ es un simbolo de ∑

si ∑ = {0,1,2,3,4,5,6,7,8,9}

*No se permiten conjuntos vacio como parte de un lenguaje*

**Palabra**: Secuencia *finita* de simbolos de un determinado alfabeto.

**Lenguaje:** es un conjunto de palabras.

{1,12,132,12345,123456} *Lenguaje finito*

{1,2,3,4,...} o {X | X>3} *Lenguaje Infinito*

Si ∑ es un alfabeto tambien es un lenguaje.
"""